erDiagram

"public.users" }o--|| "public.organizations" : "FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE"
"public.networks" }o--|| "public.organizations" : "FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE"
"public.hosts" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.subnets" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.groups" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.daemons" }o--|| "public.users" : "FOREIGN KEY (user_id) REFERENCES users(id)"
"public.daemons" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.services" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.services" }o--|| "public.hosts" : "FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE CASCADE"
"public.discovery" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.discovery" }o--|| "public.daemons" : "FOREIGN KEY (daemon_id) REFERENCES daemons(id) ON DELETE CASCADE"
"public.api_keys" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.topologies" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.tags" }o--|| "public.organizations" : "FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE"
"public.invites" }o--|| "public.users" : "FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE"
"public.invites" }o--|| "public.organizations" : "FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE"
"public.shares" }o--|| "public.users" : "FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE"
"public.shares" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.shares" }o--|| "public.topologies" : "FOREIGN KEY (topology_id) REFERENCES topologies(id) ON DELETE CASCADE"
"public.user_network_access" }o--|| "public.users" : "FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE"
"public.user_network_access" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.interfaces" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.interfaces" }o--|| "public.hosts" : "FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE CASCADE"
"public.interfaces" }o--|| "public.subnets" : "FOREIGN KEY (subnet_id) REFERENCES subnets(id) ON DELETE CASCADE"
"public.ports" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.ports" }o--|| "public.hosts" : "FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE CASCADE"
"public.bindings" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.bindings" }o--|| "public.services" : "FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE"
"public.bindings" }o--o| "public.interfaces" : "FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE"
"public.bindings" }o--o| "public.ports" : "FOREIGN KEY (port_id) REFERENCES ports(id) ON DELETE CASCADE"
"public.group_bindings" }o--|| "public.groups" : "FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE"
"public.group_bindings" }o--|| "public.bindings" : "FOREIGN KEY (binding_id) REFERENCES bindings(id) ON DELETE CASCADE"
"public.user_api_keys" }o--|| "public.users" : "FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE"
"public.user_api_keys" }o--|| "public.organizations" : "FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE"
"public.user_api_key_network_access" }o--|| "public.networks" : "FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE"
"public.user_api_key_network_access" }o--|| "public.user_api_keys" : "FOREIGN KEY (api_key_id) REFERENCES user_api_keys(id) ON DELETE CASCADE"
"public.entity_tags" }o--|| "public.tags" : "FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE"

"public._sqlx_migrations" {
  bigint version
  text description
  timestamp_with_time_zone installed_on
  boolean success
  bytea checksum
  bigint execution_time
}
"public.users" {
  uuid id
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  text password_hash
  text oidc_provider
  text oidc_subject
  timestamp_with_time_zone oidc_linked_at
  text email
  uuid organization_id FK
  text permissions
  uuid__ tags
  timestamp_with_time_zone terms_accepted_at
  boolean email_verified
  text email_verification_token
  timestamp_with_time_zone email_verification_expires
  text password_reset_token
  timestamp_with_time_zone password_reset_expires
}
"public.networks" {
  uuid id
  text name
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  uuid organization_id FK
}
"public.hosts" {
  uuid id
  uuid network_id FK
  text name
  text hostname
  text description
  jsonb source
  jsonb virtualization
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  boolean hidden
}
"public.subnets" {
  uuid id
  uuid network_id FK
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  text cidr
  text name
  text description
  text subnet_type
  jsonb source
}
"public.groups" {
  uuid id
  uuid network_id FK
  text name
  text description
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  jsonb source
  text color
  text edge_style
  text group_type
}
"public.daemons" {
  uuid id
  uuid network_id FK
  uuid host_id
  timestamp_with_time_zone created_at
  timestamp_with_time_zone last_seen
  jsonb capabilities
  timestamp_with_time_zone updated_at
  text mode
  text url
  text name
  text version
  uuid user_id FK
}
"public.services" {
  uuid id
  uuid network_id FK
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  text name
  uuid host_id FK
  text service_definition
  jsonb virtualization
  jsonb source
  integer position
}
"public.discovery" {
  uuid id
  uuid network_id FK
  uuid daemon_id FK
  jsonb run_type
  jsonb discovery_type
  text name
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
}
"public.api_keys" {
  uuid id
  text key
  uuid network_id FK
  text name
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  timestamp_with_time_zone last_used
  timestamp_with_time_zone expires_at
  boolean is_enabled
}
"public.organizations" {
  uuid id
  text name
  text stripe_customer_id
  jsonb plan
  text plan_status
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  jsonb onboarding
}
"public.topologies" {
  uuid id
  uuid network_id FK
  text name
  jsonb edges
  jsonb nodes
  jsonb options
  jsonb hosts
  jsonb subnets
  jsonb services
  jsonb groups
  boolean is_stale
  timestamp_with_time_zone last_refreshed
  boolean is_locked
  timestamp_with_time_zone locked_at
  uuid locked_by
  uuid__ removed_hosts
  uuid__ removed_services
  uuid__ removed_subnets
  uuid__ removed_groups
  uuid parent_id
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  uuid__ tags
  jsonb interfaces
  uuid__ removed_interfaces
  jsonb ports
  uuid__ removed_ports
  jsonb bindings
  uuid__ removed_bindings
}
"public.tags" {
  uuid id
  uuid organization_id FK
  text name
  text description
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  text color
}
"public.invites" {
  uuid id
  uuid organization_id FK
  text permissions
  uuid__ network_ids
  text url
  uuid created_by FK
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  timestamp_with_time_zone expires_at
  text send_to
}
"public.shares" {
  uuid id
  uuid topology_id FK
  uuid network_id FK
  uuid created_by FK
  text name
  boolean is_enabled
  timestamp_with_time_zone expires_at
  text password_hash
  text__ allowed_domains
  jsonb options
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
}
"public.user_network_access" {
  uuid id
  uuid user_id FK
  uuid network_id FK
  timestamp_with_time_zone created_at
}
"public.interfaces" {
  uuid id
  uuid network_id FK
  uuid host_id FK
  uuid subnet_id FK
  inet ip_address
  macaddr mac_address
  text name
  integer position
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
}
"public.ports" {
  uuid id
  uuid network_id FK
  uuid host_id FK
  integer port_number
  text protocol
  text port_type
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
}
"public.bindings" {
  uuid id
  uuid network_id FK
  uuid service_id FK
  text binding_type
  uuid interface_id FK
  uuid port_id FK
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
}
"public.group_bindings" {
  uuid id
  uuid group_id FK
  uuid binding_id FK
  integer position
  timestamp_with_time_zone created_at
}
"public.user_api_keys" {
  uuid id
  text key
  uuid user_id FK
  uuid organization_id FK
  text permissions
  text name
  timestamp_with_time_zone created_at
  timestamp_with_time_zone updated_at
  timestamp_with_time_zone last_used
  timestamp_with_time_zone expires_at
  boolean is_enabled
}
"public.user_api_key_network_access" {
  uuid id
  uuid api_key_id FK
  uuid network_id FK
  timestamp_with_time_zone created_at
}
"public.entity_tags" {
  uuid id
  uuid entity_id
  varchar_50_ entity_type
  uuid tag_id FK
  timestamp_with_time_zone created_at
}
"tower_sessions.session" {
  text id
  bytea data
  timestamp_with_time_zone expiry_date
}