/**
 * TanStack Query hooks for User API Keys
 * These are API keys generated by users for programmatic access
 */

import { createQuery, createMutation, useQueryClient } from '@tanstack/svelte-query';
import { queryKeys } from '$lib/api/query-client';
import { apiClient } from '$lib/api/client';
import type { components } from '$lib/api/schema';
import { utcTimeZoneSentinel, uuidv4Sentinel } from '$lib/shared/utils/formatting';

export type UserApiKey = components['schemas']['UserApiKey'];
export type UserApiKeyBase = components['schemas']['UserApiKeyBase'];
export type UserOrgPermissions = components['schemas']['UserOrgPermissions'];

/**
 * Query hook for fetching all user API keys for the current user
 */
export function useUserApiKeysQuery() {
	return createQuery(() => ({
		queryKey: queryKeys.userApiKeys.all,
		queryFn: async () => {
			const { data } = await apiClient.GET('/api/v1/auth/keys', {
				params: { query: { limit: 0 } }
			});
			if (!data?.success || !data.data) {
				throw new Error(data?.error || 'Failed to fetch user API keys');
			}
			return data.data;
		}
	}));
}

/**
 * Response type from create user API key endpoint
 */
interface CreateUserApiKeyResponse {
	key: string;
	api_key: UserApiKey;
}

/**
 * Mutation hook for creating a user API key
 * Returns the key string (only shown once) and the created API key
 */
export function useCreateUserApiKeyMutation() {
	const queryClient = useQueryClient();

	return createMutation(() => ({
		mutationFn: async (apiKey: UserApiKey) => {
			const { data } = await apiClient.POST('/api/v1/auth/keys', { body: apiKey });
			if (!data?.success || !data.data) {
				throw new Error(data?.error || 'Failed to create user API key');
			}
			const response = data.data as CreateUserApiKeyResponse;
			return { keyString: response.key, apiKey: response.api_key };
		},
		onSuccess: ({ apiKey }) => {
			queryClient.setQueryData<UserApiKey[]>(queryKeys.userApiKeys.all, (old) =>
				old ? [...old, apiKey] : [apiKey]
			);
		}
	}));
}

/**
 * Mutation hook for updating a user API key
 */
export function useUpdateUserApiKeyMutation() {
	const queryClient = useQueryClient();

	return createMutation(() => ({
		mutationFn: async (apiKey: UserApiKey) => {
			const { data } = await apiClient.PUT('/api/v1/auth/keys/{id}', {
				params: { path: { id: apiKey.id } },
				body: apiKey
			});
			if (!data?.success || !data.data) {
				throw new Error(data?.error || 'Failed to update user API key');
			}
			return data.data;
		},
		onSuccess: (updatedKey: UserApiKey) => {
			queryClient.setQueryData<UserApiKey[]>(
				queryKeys.userApiKeys.all,
				(old) => old?.map((k) => (k.id === updatedKey.id ? updatedKey : k)) ?? []
			);
		}
	}));
}

/**
 * Mutation hook for deleting a user API key
 */
export function useDeleteUserApiKeyMutation() {
	const queryClient = useQueryClient();

	return createMutation(() => ({
		mutationFn: async (id: string) => {
			const { data } = await apiClient.DELETE('/api/v1/auth/keys/{id}', {
				params: { path: { id } }
			});
			if (!data?.success) {
				throw new Error(data?.error || 'Failed to delete user API key');
			}
			return id;
		},
		onSuccess: (id: string) => {
			queryClient.setQueryData<UserApiKey[]>(
				queryKeys.userApiKeys.all,
				(old) => old?.filter((k) => k.id !== id) ?? []
			);
		}
	}));
}

/**
 * Mutation hook for bulk deleting user API keys
 */
export function useBulkDeleteUserApiKeysMutation() {
	const queryClient = useQueryClient();

	return createMutation(() => ({
		mutationFn: async (ids: string[]) => {
			const { data } = await apiClient.POST('/api/v1/auth/keys/bulk-delete', { body: ids });
			if (!data?.success) {
				throw new Error(data?.error || 'Failed to delete user API keys');
			}
			return ids;
		},
		onSuccess: (ids: string[]) => {
			queryClient.setQueryData<UserApiKey[]>(
				queryKeys.userApiKeys.all,
				(old) => old?.filter((k) => !ids.includes(k.id)) ?? []
			);
		}
	}));
}

/**
 * Mutation hook for rotating a user API key
 */
export function useRotateUserApiKeyMutation() {
	return createMutation(() => ({
		mutationFn: async (keyId: string) => {
			const { data } = await apiClient.POST('/api/v1/auth/keys/{id}/rotate', {
				params: { path: { id: keyId } }
			});
			if (!data?.success || !data.data) {
				throw new Error(data?.error || 'Failed to rotate user API key');
			}
			return data.data as string;
		}
	}));
}

/**
 * Create empty form data for a new user API key
 */
export function createEmptyUserApiKeyFormData(): UserApiKey {
	return {
		id: uuidv4Sentinel,
		name: '',
		created_at: utcTimeZoneSentinel,
		updated_at: utcTimeZoneSentinel,
		expires_at: null,
		last_used: null,
		key: '',
		is_enabled: true,
		tags: [],
		user_id: uuidv4Sentinel,
		organization_id: uuidv4Sentinel,
		permissions: 'Viewer',
		network_ids: []
	};
}
